// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGKjj3T1dodVgUboXboKi2XN2ZOfnUMKU',
    appId: '1:727201035888:web:8000f6719f05d7a40126b5',
    messagingSenderId: '727201035888',
    projectId: 'niamcity-firebase',
    authDomain: 'niamcity-firebase.firebaseapp.com',
    storageBucket: 'niamcity-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP8pXQAcCNJ-uFlTIMIulQ8R3ZV49Woak',
    appId: '1:727201035888:android:bf9b930c3926f4a10126b5',
    messagingSenderId: '727201035888',
    projectId: 'niamcity-firebase',
    storageBucket: 'niamcity-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmAz-PzHyZugMNPQyfR3FGSFhO5oP0Vjs',
    appId: '1:727201035888:ios:ff4a50022c03b11d0126b5',
    messagingSenderId: '727201035888',
    projectId: 'niamcity-firebase',
    storageBucket: 'niamcity-firebase.appspot.com',
    iosBundleId: 'com.example.niamcity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmAz-PzHyZugMNPQyfR3FGSFhO5oP0Vjs',
    appId: '1:727201035888:ios:10d3d2f2de9a45ec0126b5',
    messagingSenderId: '727201035888',
    projectId: 'niamcity-firebase',
    storageBucket: 'niamcity-firebase.appspot.com',
    iosBundleId: 'com.example.niamcity.RunnerTests',
  );
}
